### ISSUE TITLE
2. Proposal

### ISSUE THREAD

**Issue by fatse** [UBC-MDS/Mental-Health-in-Tech-Dashboard#2]
Your proposal should be no more than 1,000 words and include a sketch of your app. The proposal should be written as a markdown document (proposal.md) in your GitHub.com repo and include the following sections:

- [x]  1. [Motivation and purpose](https://github.com/UBC-MDS/group-19/issues/4#issuecomment-761043581)

- [x] 2. [Description of the data](https://github.com/UBC-MDS/group-19/issues/5)

- [x]  3. [Research questions you are exploring](https://github.com/UBC-MDS/group-19/issues/4#issuecomment-760619686)

- [x]  4. You will be assessed on the reasoning underlying your proposal as well as the quality and clarity of your writing.
