### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by fatse** [UBC-MDS/Mental-Health-in-Tech-Dashboard#20]
- [x] 1. Submission instructions: 
- The only file you need to submit to Canvas is the one called canvas-submission.html

- [x] 2. Deployment on Heroku
- [x] 3. Interactive Dash app in Python and Altair
- [x] 4. Reflection
- [ ] 5. Improve the README (Optional)

**Comment by d-sel** [comment]
- add in own plot to app.py (@fatse @chiragrank @mikelynch416 )
- add bootstrap to layout @d-sel 
- reflection (issue to be created after deployment Friday)
- Heroku (@fatse @chiragrank )
- improvement to README (@fatse )

**Comment by chiragrank** [comment]
Meeting notes Friday 22 January 2021
- Update on the Heroku server along with pull request acceptance @fatse @chiragrank @mikelynch416 @d-sel 
- ~~fourth plot addition @fatse~~
- aligning the visualization
  - First: 
    - Title
    - Figure size
    - horizontal vs vertical
    - vertical scroll
    - y-axis label "Number of Responses"
    - rename Null to give more specific interpretation
    - Real Question instead variables and insert title (Optional) @chiragrank 
  - Second:
    - Color by bars
    - Age filter label
  - Third
   - ~~X axis remove~~
   - ~~rename Mental health disorder~~
   - ~~sideway scroll~~
   - ~~y-axis label "Number of responses"~~
- Reflection draft @mikelynch416
- Final touch aligned dashboard
- Update with gifs (Optional)
- Change the layout
  - ~~Shrink~~
  - Section for the first plot

**Comment by d-sel** [comment]
First plot:
- Title: _fixed to be varying based on title; however, still need to fix question item (optional below)_
- Figure size: _fixed_
- horizontal vs vertical: _I tried the horizontal bars, but, from my perspective, the responses are more difficult to read, so I've reverted to vertical._
![image](https://user-images.githubusercontent.com/70779928/105570239-d3ceee00-5cfc-11eb-9a95-92c2460f71a2.png)
- vertical scroll: _fixed_
- y-axis label "Number of Responses": _fixed_

Remaining:
- rename Null to give more specific interpretation
- Real Question instead variables and insert title (Optional) @chiragrank
     - I'm having some trouble with this. Once all other to-do's are done, perhaps we can see if someone else can help figure out how to do this within the context of dash
