### ISSUE TITLE
Instructor's Milestone 2 Feedback

### ISSUE THREAD

**Issue by fatse** [UBC-MDS/Mental-Health-in-Tech-Dashboard#35]
Joel's feedback during the Lab session for our dashboard:

<hr>

**First plot** (Overview Tab)
  - [x] Using facets for male/female responses
  - [x] Ordering for the different questions that can be supported by ordering 

**Last plot** (donut chart) 
  - [x] might look nicer if we adjust the width to match the width of the other plots

**Overall feedback**
  - [x] Add color to the background instead of leaving it just plain white
  - [x] Use the same font in the app, i.e. match the fonts in all text fields.
<hr>

Feel free to add anything that Joel said during our lab session and I might have forgotten to include here.

**Comment by fatse** [comment]
All the points above have been addressed. Closing this issue.
