### ISSUE TITLE
Checklist for Milestone 4 Implementations/Improvements

### ISSUE THREAD

**Issue by fatse** [UBC-MDS/Mental-Health-in-Tech-Dashboard#37]
Dash app link: https://mentalhealth-in-tech.herokuapp.com/

<hr>

### TA's feedback:

- [x] On pie charts I likes the double clicking module but it doesn't do anything extra as it isolates one variable which covers 100% of the chart.
- [x] on second row of charts from the top: "Does your mental health..."
- 1- arrange the order of legend to match the chart
- 2- It would be great it you could make both charts to have the same scale for "number of responses". It would make comparison easier.

<hr>

### Peer Feedback:

Link: https://github.com/UBC-MDS/Mental-Health-in-Tech-Dashboard-R/issues/11

- [x] Maybe it can be useful to include a short description in the overview section
- [x] The colors of countries in the pie chart. For example, UK has different colors. Maybe it would be better to have one color represent each country across all three pies. (We know pie charts are hard to make, so if this adjustment is time-consuming, do not worry about it :D )
- [x] Maybe a very short intro of the app on top

<hr>

### Milestone 3 implementations:

**First plot:**
- [x] Using facets for male/female responses (@d-sel )
- [x] Ordering for the different questions that can be supported by ordering (@d-sel )

**Second and third plot:**

- [x] Oder x-axis and align y-axis between the two plots (@mikelynch416 )
- [x] Use single color instead of legends (@chiragrank @mikelynch416 )

**Last plot:**

- [x]  adjust the width to match the width of the other plots (@fatse )
- [x] Fix padding on top and bottom of the plots (@fatse )

**Styling improvements:** 

- [x] Add color to the background instead of leaving it just plain white (ALL)
- [x] Use the same font in the app, i.e. match the fonts in all text fields (@mikelynch416 )
- [x] Style heading (ALL)
- [x] Set the title of the browser tab of your app by using the title parameter when calling Dash() (@fatse )
- [x] Add tabs (collapsable menu) - 3 tabs for each section, i.e. Overview, HR Questions Section, Benefits questions (@chiragrank )
- [x] Order radio buttons vertically on the second/third plot (@fatse )
- [x] Add cards for plots that make sense to be in a card (?)
- [x] Improve overall layout (ALL)
~- [ ] Potentially switch from radio buttons to checkboxes (?)~
- [ ] Improve performance (@fatse )
- [x] Add docstrings for each function (app.py) (ALL)
- [x] Setup Heroku's GitHub integration to automate deploys so that you have a branch in your GitHub repo that is automatically deployed to Heroku (@fatse )
- [x] Add "About us" on the footer of the app (@fatse )
- [x] Overview description (@mikelynch416 )
